apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
spec:
  replicas: 1 # Cambiar para pruebas 1, 2 o 3
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend-app
        image: backend-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: postgres
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          value: postgres
        - name: DB_NAME
          value: testdb
---
apiVersion: v1
kind: Service
metadata:
  name: backend-app-service
spec:
  type: NodePort
  selector:
    app: backend-app
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30080